DROP DATABASE IF EXISTS `temp`;
CREATE DATABASE `temp` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

USE `temp`;

DROP TABLE IF EXISTS `USERS`;
CREATE TABLE USERS (
    USER_ID BIGINT NOT NULL AUTO_INCREMENT,
    USER_NAME VARCHAR(60) NOT NULL,
    LOGIN VARCHAR(20) NOT NULL,
    PSWD VARCHAR(20) NOT NULL,
    USER_ENABLED BIT NOT NULL DEFAULT 1,
    UNIQUE UNIQUE_USER_ID (USER_ID),
    UNIQUE UNIQUE_USER_LOGIN (LOGIN),
    UNIQUE UNIQUE_USER_NAME (USER_NAME),
    PRIMARY KEY (USER_ID)
    );

DROP TABLE IF EXISTS `ROLES`;
CREATE TABLE ROLES (
    ROLE_ID INT NOT NULL AUTO_INCREMENT,
    ROLE_NAME VARCHAR(20) NOT NULL,
    UNIQUE UNIQUE_ROLE_NAME (ROLE_NAME),
    PRIMARY KEY (ROLE_ID)
    );

DROP TABLE IF EXISTS `USER_ROLES`;
CREATE TABLE USER_ROLES (
    UR_USER_ID BIGINT NOT NULL,
    UR_ROLE_ID INT NOT NULL,
    UR_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE UNIQUE_USER_ROLES (UR_USER_ID, UR_ROLE_ID),
    FOREIGN KEY(UR_USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY(UR_ROLE_ID) REFERENCES ROLES(ROLE_ID) ON DELETE CASCADE
    );

DROP TABLE IF EXISTS `USER_STATISTIC`;
CREATE TABLE USER_STATISTIC (
    USER_STATISTIC_ID BIGINT NOT NULL,
    US_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
    US_VIEWED_COUNT BIGINT NOT NULL DEFAULT 0,
    UNIQUE UNIQUE_USER_STATISTIC (USER_STATISTIC_ID),
    FOREIGN KEY(USER_STATISTIC_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    PRIMARY KEY (USER_STATISTIC_ID)
    );

DROP TABLE IF EXISTS `INTERNATIONAL_MESSAGES`;
CREATE TABLE INTERNATIONAL_MESSAGES (
    INTERNATIONAL_MESSAGES_ID BIGINT NOT NULL AUTO_INCREMENT,
    IM_CODE VARCHAR(40) NOT NULL,
    IM_LOCALE VARCHAR(15) NOT NULL,
    IM_DATA TEXT NOT NULL,
    UNIQUE UNIQUE_INTERNATIONAL_MESSAGES (IM_CODE, IM_LOCALE),
    PRIMARY KEY (INTERNATIONAL_MESSAGES_ID)
    );